name: Audit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: macos-latest
    env:
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Tap local repository
        run: brew tap AnalyseDeCircuit/tap "$GITHUB_WORKSPACE"

      - name: Style cask
        run: brew style --cask AnalyseDeCircuit/tap/oxideterm

      - name: Audit cask
        run: brew audit --cask --online AnalyseDeCircuit/tap/oxideterm
